### PR TITLE
Visual Studio 2017 has platform toolset v141, not v150

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by ocielliottc** [comment]
Where is the ChangeLog entry?

**Comment by jwillemsen** [comment]
Do you want to maintain a manual changelog for MPC? None of the other repositories do that anymore. Using the git commit messages this can easily be created if necessary and having a manual changelog is a nightmare when merging changes, anything you do causes merge conflicts and manual work to resolve those.

**Comment by ocielliottc** [comment]
Yes.  We need to maintain a ChangeLog, otherwise the micro version of
MPC is not changed.

**Comment by jwillemsen** [comment]
Can't the hash of the latest git commit be used?

**Comment by ocielliottc** [comment]
I don't know.  Can that automatically be inserted into the code upon commit?

**Comment by jwillemsen** [comment]
It can easily be retrieved using the git client

**Pull request merged**
