### PR TITLE
Enable MultiProcessorCompilation by default for Visual Studio 2019/20…

### PR DESCRIPTION
**Pull request by jwillemsen**
…22, will speedup compilation

    * templates/vs2019platforms.mpt:
    * templates/vs2022platforms.mpt:

### CODE REVIEW

**Comment by jwillemsen** [comment]
Will speedup compilation by compiling multiple files within one project in parallel

**Review by mitza-oci — COMMENTED** [review]
Default for Visual Studio seems to be to not have this enabled (no `/MP` in complier options). Is there a reason they don't have it on?

**Comment by jwillemsen** [comment]
No idea why don't have it on as default, maybe history. This really speeds up compilation on modern machines with a lot of cores, especially when working on ACE itself. With TAO at some point multiple projects are compiled in parallel, but this saves a lot of time.

**Comment by mitza-oci** [comment]
Just for another point of comparison, CMake doesn't seem to generate projects with this enabled.
Based on [documentation](https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170) it may be better as a project-specific setting instead of defaulting for all projects.

**Comment by jwillemsen** [comment]
Ok, will close this one and open a PR on the core ACE library to add this flag

**Pull request closed without merging**
