### PR TITLE
Generate Visual Studio 2022 projects and solutions

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Review by jwillemsen — APPROVED** [review]

**Comment by jwillemsen** [comment]
At the moment ACE works with vs2022 the github action here in MPC should be extended to also build with vs2022

**Comment by mitza-oci** [comment]
> 
> 
> At the moment ACE works with vs2022 the github action here in MPC should be extended to also build with vs2022

GitHub Actions is still on the preview version
https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

I don't know of any ACE changes that are required, but haven't tried a full build.  libACE looks OK.

**Comment by jwillemsen** [comment]
Looks some more places maybe need to be updated 

* https://github.com/DOCGroup/MPC/blob/1abb954e30a844c28ac45af64fbaadd7915a2610/registry.pl#L40 has a check for vs2019,
* docs/html/MakeProjectCreator.html lists vs2019
* * some mpb lists vs2019

**Comment by jwillemsen** [comment]
> I suggest we take the opportunity to make these `prop:microsoft` (or similar). VS2009 isn't supported anymore.

Sounds a good proposal, maybe in ACE/TAO/OpenDDS we can do similar cleanup

**Review by jwillemsen — APPROVED** [review]

**Pull request merged**
