### PR TITLE
Adds the possibility for static Visual Studio projects to link to the…

### PR DESCRIPTION
**Pull request by pierrebizz**
… DLL runtime libraries  -value_template useDynamicSystemLibraries+=1

The idea is to support vcpkg x64-windows-static-md for ACE

### CODE REVIEW

**Comment by pierrebizz** [comment]
I fail to understand why the 32 bits build fails on tao_idl invocation; I know that tao_idl will fail if cl.exe is not in the path; is that the case ?

**Comment by jwillemsen** [comment]
Have you tried to build and run this locally? It is true that tao_idl uses cl, but that does work before your change on github actions, so this must be something related to the runtime library change you are making.

**Comment by pierrebizz** [comment]
type_is_dynamic was not the correct flag for the executable built (like gperf and tao_idl)
I'm relying on need_staticflags instead

**Comment by pierrebizz** [comment]
I just noticed that the flag runtime_library might be used to set the link with dynamic runtime libraries but still generate libraries instead of dlls; I will try it later

**Comment by mitza-oci** [comment]
@pierrebizz can this be closed?

**Comment by pierrebizz** [comment]
> @pierrebizz can this be closed?

Yes !

**Pull request closed without merging**
