### PR TITLE
Allow multiple combined custom types to have the same command.

### PR DESCRIPTION
**Pull request by ocielliottc**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Could you add an example to the documentation of what of is possible with this change?

**Comment by ocielliottc** [comment]
> I was not able to build OpenDDS (DDS.mwc) on vs2022 using this branch of MPC.
> 
> The first error I saw was in project `InfoRepo_Population_SyncServer`. It has an IDL file `SyncExt.idl` which is only supposed to processed with `tao_idl`, not `opendds_idl`. The generated project ran both `tao_idl` and `opendds_idl`.

I believe I have corrected this problem.  The interesting thing is that it didn't consistently show itself.  I am guessing it had something to do with the way things were read from the file system.

**Comment by ocielliottc** [comment]
> Could you add an example to the documentation of what of is possible with this change?

This is a bug fix for "Combined Custom".

**Review by mitza-oci — APPROVED** [review]

**Comment by ocielliottc** [comment]
> Btw, because you branch on the main MPC github repository each change triggers the github actions CI twice using the DOCGroup organization free workers, when you would fork MPC and work from that fork you will use your own free github workers and the one from the DOCGroup, making more room for others on the DOCGroup account

Thanks.  I'll keep that in mind for next time.

**Pull request merged**
