### PR TITLE
Default to x64 as default Visual Studio 2017/2019 platform

### PR DESCRIPTION
**Pull request by jwillemsen**
* templates/vs2017platforms.mpt:
    * templates/vs2019platforms.mpt:

### CODE REVIEW

**Comment by mitza-oci** [comment]
Why did this change?

**Comment by jwillemsen** [comment]
Changed the default to x64 as i686 is hardly used anymore but still is the default for any project opened in the IDE

**Comment by mitza-oci** [comment]
Before this change solutions generated by MPC (by default) were configured the same way as solutions created directly in VS.

**Comment by jwillemsen** [comment]
> Before this change solutions generated by MPC (by default) were configured the same way as solutions created directly in VS.

Ok, missed that, just tried here and yes, 32bit is the default (still find that strange), opened a PR to revert this one

**Pull request merged**
