### PR TITLE
Add support for Visual Studio 2019 using Visual C++ 14.2

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by mitza-oci** [comment]
Since VS2019 is at the moment just a preview, we should keep these changes on a branch.  MPC's master branch is implicitly released when ACE_TAO is released.

**Comment by jwillemsen** [comment]
With this on master it would make it easier for people to test their code with vs2019 preview

**Comment by mitza-oci** [comment]
Users that are going to the trouble of installing pre-release development tools can use a branch of MPC.  The way this repo gets used, master needs to be "release ready" at all times.  If some important detail in VS2019 changes before it gets released, that change will be difficult to manage for downstream projects.

**Comment by jwillemsen** [comment]
Release is scheduled for April 2 2019, see https://visualstudio.microsoft.com/vs2019-launch/

**Comment by jwillemsen** [comment]
See https://github.com/Microsoft/azure-pipelines-image-generation/issues/268#issuecomment-459418357 for the work in progress to add Visual Studio 2019 to azure devops

**Comment by jwillemsen** [comment]
@mitza-oci the ace/tao pull request to compile on azure with vs2019 is now green

**Pull request merged**
