### PR TITLE
Set default Windows SDK version to the one that VS2017 installs.

### PR DESCRIPTION
**Pull request by mitza-oci**

### CODE REVIEW

**Comment by jwillemsen** [comment]
@mitza-oci Looks something we should merge

**Comment by mitza-oci** [comment]
It would be nice if we had a better way to handle this since it may change again with another minor version of VS2017.

I was thinking of merging it when #50 is done.

**Comment by jwillemsen** [comment]
The regular msvc updates are positive but it has disadvantages

**Comment by jwillemsen** [comment]
@mitza-oci Can we merge this one now?

**Comment by tottens** [comment]
> It would be nice if we had a better way to handle this since it may change again with another minor version of VS2017.

Is it possible to require a _minimum_ version of the Windows SDK, but not a specific version, so a Windows SDK update installed by a minor update to VS2017 would still be accepted?

**Comment by jwillemsen** [comment]
For vs2019 we merged #88, maybe try the same with vs2017

**Pull request merged**
